### ISSUE TITLE
Implement Travis CI

### ISSUE THREAD

**Issue by MitchellCash** [PaycoinFoundation/paycoinj#9]
Can we please implement Travis CI for automated testing of pulls.

I've been testing it myself, which can be seen on some example pulls on my test repo here: https://github.com/mitchellcash/paycoinj-travis/pulls

Example YAML file can also be found here: https://github.com/mitchellcash/paycoinj-travis/blob/master/.travis.yml

Mimicked concepts from bitcoinj.

**Comment by PaycoinMaster** [comment]
Added
